### ISSUE TITLE
spfk

### ISSUE THREAD

**Issue by m1kadev** [itsmebombie/SPFK#1]
it looks like spck

**Comment by Unzor** [comment]
maybe sfck (sickfuck 😳 )

**Comment by Unzor** [comment]
rename to SFCK @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie @itsmebombie

**Comment by itsmebombie** [comment]
no spfk means specky why did you steal my name fuck😡

**Comment by itsmebombie** [comment]
> it looks like spck

true

**Comment by Unzor** [comment]
y u delte comeints 😡
